package sample.config;

import org.springframework.security.oauth2.server.authorization.OAuth2Authorization;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;
import org.springframework.security.oauth2.server.authorization.web.UserConsentPage;

import javax.servlet.http.HttpServletRequest;

/**
 * User defined consent authorization return page content
 *
 * @author shanhy
 * @date 2021/3/30 15:55
 */
public class CustomUserConsentPage implements UserConsentPage {

	/**
	 * Returns the HTML content of a custom authorization page
	 *
	 * You can splice HTML
	 * (recommended) HTML can also be generated by freemarker template
	 *
	 * @param request
	 * @param registeredClient
	 * @param authorization
	 * @return
	 */
	@Override
	public String generateConsentPage(HttpServletRequest request, RegisteredClient registeredClient, OAuth2Authorization authorization) {
		// This is the default. You can customize the content you need
		return this.generateConsentPage(request, registeredClient, authorization);
	}

}
