[[how-to-jpa]]
= How-to: Implement core services with JPA
:index-link: ../how-to.html
:docs-dir: ..
:examples-dir: ../examples

[[jpa-getting-started]]
== Getting Started

This guide shows how to implement the xref:{docs-dir}/core-model-components.adoc#core-model-components[core services] of xref:{docs-dir}/index.adoc#top[Spring Authorization Server] with JPA.
The purpose of this guide is to provide a starting point for implementing these services yourself, with the intention that you can make modifications to suit your needs.

[[jpa-define-data-model]]
== Define the data model

This guide provides a starting point for the data model and uses the simplest possible structure and data types.
To come up with the initial schema, we begin by reviewing the xref:{docs-dir}/core-model-components.adoc#core-model-components[domain objects] used by the core services.

NOTE: Except for token, state, metadata, settings, and claims values, we use the JPA default column length of 255 for all columns.
In reality, the length and even type of columns you use may need to be customized.
You are encouraged to experiment and test before deploying to production.

[[jpa-client-schema]]
=== Client Schema

The xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object contains a few multi-valued fields and some settings fields that require storing arbitrary key/value data.
The following listing shows the `client` schema.

.Client Schema
[source,sql]
----
include::{examples-dir}/src/main/resources/oauth2-registered-client-schema.sql[]
----

[[jpa-authorization-schema]]
=== Authorization Schema

The xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] domain object is more complex and contains several multi-valued fields as well as numerous arbitrarily long token values, metadata, settings and claims values.
The built-in JDBC implementation utilizes a flattened structure that prefers performance over normalization, which we adopt here as well.

CAUTION: It has been difficult to find a flattened database schema that works well in all cases and with all database vendors.
You may need to normalize or heavily alter the following schema for your needs.

The following listing shows the `authorization` schema.

.Authorization Schema
[source,sql]
----
include::{examples-dir}/src/main/resources/oauth2-authorization-schema.sql[]
----

[[jpa-authorization-consent-schema]]
=== Authorization Consent Schema

The xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2AuthorizationConsent`] domain object is the simplest to model and contains only a single multi-valued field in addition to a composite key.
The following listing shows the `authorizationConsent` schema.

.Authorization Consent Schema
[source,sql]
----
include::{examples-dir}/src/main/resources/oauth2-authorization-consent-schema.sql[]
----

[[jpa-create-jpa-entities]]
== Create JPA entities

The preceding schema examples provide a reference for the structure of the entities we need to create.

NOTE: The following entities are minimally annotated and are just examples.
They allow the schema to be created dynamically and therefore do not require the above sql scripts to be executed manually.

[[jpa-client-entity]]
=== Client Entity

The following listing shows the `Client` entity, which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object.

.Client Entity
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/Client.java[tag=class]
----

[[jpa-authorization-entity]]
=== Authorization Entity

The following listing shows the `Authorization` entity, which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] domain object.

.Authorization Entity
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/Authorization.java[tag=class]
----

[[jpa-authorization-consent-entity]]
=== Authorization Consent Entity

The following listing shows the `AuthorizationConsent` entity, which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2AuthorizationConsent`] domain object.

.Authorization Consent Entity
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/AuthorizationConsent.java[tag=class]
----

[[jpa-create-spring-data-repositories]]
== Create Spring Data repositories

By closely examining the interfaces of each core service and reviewing the `Jdbc` implementations, we can derive a minimal set of queries needed for supporting a JPA version of each interface.

[[jpa-client-repository]]
=== Client Repository

The following listing shows the `ClientRepository`, which is able to find a <<jpa-client-entity,`Client`>> by the `id` and `clientId` fields.

.Client Repository
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/ClientRepository.java[tag=class]
----

[[jpa-authorization-repository]]
=== Authorization Repository

The following listing shows the `AuthorizationRepository`, which is able to find an <<jpa-authorization-entity,`Authorization`>> by the `id` field as well as the `state`, `authorizationCodeValue`, `accessTokenValue` and `refreshTokenValue` token fields.
It also allows querying a combination of token fields.

.Authorization Repository
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/AuthorizationRepository.java[tag=class]
----

[[jpa-authorization-consent-repository]]
=== Authorization Consent Repository

The following listing shows the `AuthorizationConsentRepository`, which is able to find and delete an <<jpa-authorization-consent-entity,`AuthorizationConsent`>> by the `registeredClientId` and `principalName` fields that form a composite primary key.

.Authorization Consent Repository
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/AuthorizationConsentRepository.java[tag=class]
----

[[jpa-implement-core-services]]
== Implement core services

With the above <<jpa-create-jpa-entities,entities>> and <<jpa-create-spring-data-repositories,repositories>>, we can begin implementing the core services.
By reviewing the `Jdbc` implementations, we can derive a minimal set of internal utilities for converting to and from string values for enumerations and reading and writing JSON data for attributes, settings, metadata and claims fields.

CAUTION: Keep in mind that writing JSON data to text columns with a fixed length has proven problematic with the `Jdbc` implementations.
While these examples continue to do so, you may need to split these fields out into a separate table or data store that supports arbitrarily long data values.

[[jpa-registered-client-repository]]
=== Registered Client Repository

The following listing shows the `JpaRegisteredClientRepository`, which uses a <<jpa-client-repository,`ClientRepository`>> for persisting a <<jpa-client-entity,`Client`>> and maps to and from the xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object.

.`RegisteredClientRepository` Implementation
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/JpaRegisteredClientRepository.java[tag=class]
----

[[jpa-authorization-service]]
=== Authorization Service

The following listing shows the `JpaOAuth2AuthorizationService`, which uses an <<jpa-authorization-repository,`AuthorizationRepository`>> for persisting an <<jpa-authorization-entity,`Authorization`>> and maps to and from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] domain object.

.`OAuth2AuthorizationService` Implementation
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/JpaOAuth2AuthorizationService.java[tag=class]
----

[[jpa-authorization-consent-service]]
=== Authorization Consent Service

The following listing shows the `JpaOAuth2AuthorizationConsentService`, which uses an <<jpa-authorization-consent-repository,`AuthorizationConsentRepository`>> for persisting an <<jpa-authorization-consent-entity,`AuthorizationConsent`>> and maps to and from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2AuthorizationConsent`] domain object.

.`OAuth2AuthorizationConsentService` Implementation
[source,java]
----
include::{examples-dir}/src/main/java/sample/jpa/JpaOAuth2AuthorizationConsentService.java[tag=class]
----
